### ISSUE TITLE
Python `seekers` require external libraries not noted in the README.md

### ISSUE THREAD

**Issue by CuriouslyCurious** [Tmplt/bookwyrm#34]
The Python script `libgen.py` requires the following external libraries to work (for me at least):
* furl
* requests
* isbnlib

These are not listed in the README.md and should probably just be automagically downloaded if possible when building the project, otherwise they should be stated as requirements for certain 'seekers' to work.

**Comment by Tmplt** [comment]
While convenient, automatically downloading requiring Python libraries will most likely be frowned upon; there are many different ways to install one, and choosing one way would totally disregard the other. Best way to resolve this is probably to list them in the readme. Downstream, these can be marked as dependencies for bookwyrm.

Some libraries (e.g. `isbnlib`) could be optional, since they don't contribute as much information as others (`requests`, which does the heavy lifting). These libraries should be marked as such.
